spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Maorzehavi/coupon-crunch-config
          default-label: main
server:
  port: 8888